ALTER TABLE "Customers"
  ADD COLUMN IF NOT EXISTS "Customer Number" TEXT,
  ADD COLUMN IF NOT EXISTS "Contact Name" TEXT,
  ADD COLUMN IF NOT EXISTS "Email" TEXT,
  ADD COLUMN IF NOT EXISTS "Phone" TEXT,
  ADD COLUMN IF NOT EXISTS "Status" TEXT NOT NULL DEFAULT 'Active',
  ADD COLUMN IF NOT EXISTS "Created At" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE UNIQUE INDEX IF NOT EXISTS "Customers_Customer Number_key"
  ON "Customers" ("Customer Number");

DROP TABLE IF EXISTS "Customer";
